"""Dispatch to responders (FR6.2 email, FR6.3 responder comms).

The prototype's alert is SIMULATED by default (decision D4/D6): dispatch is
recorded in the GUI's responder panel and the append-only log, but nothing
leaves the machine. To "impress the facilitator" with a realistic call-out, the
channel can be switched to `email`, which sends the dispatch record to the
configured responder via SMTP (Gmail app password or any SMTP/Resend relay).

SAFETY: emails are NEVER sent unless `dispatch_channel == "email"` AND SMTP
credentials are present in the environment / .env. Tests use a fake SMTP server
so the dispatch logic is proven without sending a single real message.
"""
from __future__ import annotations

import os
import smtplib
import ssl
from dataclasses import dataclass
from email.message import EmailMessage
from typing import Optional


@dataclass
class EmailConfig:
    smtp_host: str = "smtp.gmail.com"
    smtp_port: int = 465
    sender: str = ""
    password: str = ""
    use_tls: bool = True

    @classmethod
    def from_env(cls) -> "EmailConfig":
        return cls(
            smtp_host=os.getenv("MTEAS_SMTP_HOST", "smtp.gmail.com"),
            smtp_port=int(os.getenv("MTEAS_SMTP_PORT", "465")),
            sender=os.getenv("MTEAS_SMTP_USER", ""),
            password=os.getenv("MTEAS_SMTP_PASS", ""),
            use_tls=os.getenv("MTEAS_SMTP_TLS", "1") != "0",
        )

    def is_configured(self) -> bool:
        return bool(self.sender and self.password)


def build_email(responder: str, dispatch_text: str, subject: Optional[str] = None) -> EmailMessage:
    msg = EmailMessage()
    msg["Subject"] = subject or "MTEAS EMERGENCY DISPATCH"
    msg["From"] = "MTEAS Device <no-reply@mteas.local>"
    msg["To"] = responder
    msg.set_content(
        "This is an automated emergency dispatch from the MTEAS device.\n\n"
        + dispatch_text
        + "\n\n(This message was generated by the MTEAS prototype.)"
    )
    return msg


def send_email(
    responder: str,
    dispatch_text: str,
    email_cfg: Optional[EmailConfig] = None,
    subject: Optional[str] = None,
    smtp_cls=smtplib.SMTP_SSL,
) -> bool:
    """Send `dispatch_text` to `responder`. Returns True if a real email was
    attempted. Raises only on explicit misconfiguration when channel=email.

    `smtp_cls` is injectable so tests can pass a fake SMTP server.
    """
    email_cfg = email_cfg or EmailConfig.from_env()
    if not email_cfg.is_configured():
        raise RuntimeError("Email dispatch not configured (set MTEAS_SMTP_USER/PASS)")
    msg = build_email(responder, dispatch_text, subject)
    ctx = ssl.create_default_context() if email_cfg.use_tls else None
    with smtp_cls(email_cfg.smtp_host, email_cfg.smtp_port, context=ctx) as server:
        server.login(email_cfg.sender, email_cfg.password)
        server.send_message(msg)
    return True
